name: Build llama.cpp
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0,12 * * *'
env:
  LOCAL_REPO: "IceDragon0145/llama.cpp-build"
  REMOTE_REPO: "ggerganov/llama.cpp"
jobs:
  ubuntu2204-cu122:
    runs-on: ubuntu-latest
    env:
      UBUNTU_VERSION: 22.04
      CUDA_VERSION: 12.2.0
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Check for latest tag
        run: /bin/sh "$GITHUB_WORKSPACE/check.sh"
      - name: Build llama.cpp with Docker
        run: /bin/sh "$GITHUB_WORKSPACE/docker.sh"
      - name: Upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: /bin/sh "$GITHUB_WORKSPACE/release.sh"
